# Generated by Django 3.1 on 2020-08-26 14:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200823_2220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('user_manager', users.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
