# Generated by Django 3.1 on 2020-08-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mealcategory',
            old_name='department_id',
            new_name='department',
        ),
    ]
