# Generated by Django 3.1.1 on 2020-09-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20200905_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food.order'),
        ),
    ]
