# Generated by Django 3.1.1 on 2020-09-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20200905_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_id', to='food.order'),
        ),
    ]
