# Generated by Django 3.1.1 on 2020-09-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20200905_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='food.order')),
                ('servicefee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefee', to='food.servicepercentage')),
            ],
        ),
    ]
