# Generated by Django 3.1.1 on 2020-09-06 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_check_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='food.order'),
        ),
    ]
