# Generated by Django 3.1.1 on 2020-09-06 03:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20200906_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 6, 3, 40, 12, 415045, tzinfo=utc)),
        ),
    ]
