# Generated by Django 3.1.1 on 2020-09-11 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20200906_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table',
            new_name='table_id',
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 11, 14, 48, 51, 305724, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='OrderedMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('meal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_meal', to='food.meal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_id', to='food.order')),
            ],
        ),
    ]
