# Generated by Django 3.1.1 on 2020-09-11 15:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20200911_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 11, 15, 14, 57, 832550, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderedmeal',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food.order'),
        ),
    ]
