# Generated by Django 3.1.1 on 2020-09-11 17:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20200911_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealtoorder',
            name='meal',
        ),
        migrations.AddField(
            model_name='mealtoorder',
            name='meal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='menu_meal', to='food.meal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 11, 17, 27, 39, 4484, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mealtoorder',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mealtoorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='food.order'),
        ),
        migrations.DeleteModel(
            name='OrderedMeal',
        ),
    ]
