# Generated by Django 3.1.1 on 2020-09-11 17:39

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20200911_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepercentage',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 11, 17, 38, 58, 958740, tzinfo=utc)),
        ),
    ]
