# Generated by Django 3.1.1 on 2020-09-11 17:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20200911_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepercentage',
            name='order',
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 9, 11, 17, 49, 6, 510963, tzinfo=utc)),
        ),
    ]
