# Generated by Django 3.1.1 on 2020-09-11 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_auto_20200911_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.order'),
        ),
        migrations.AlterField(
            model_name='check',
            name='servicefee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.servicepercentage'),
        ),
        migrations.DeleteModel(
            name='Checks',
        ),
    ]
