# Generated by Django 3.1.1 on 2020-09-11 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_auto_20200912_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='meal',
        ),
    ]
